// In this file you can specify the trial data for your experiment

const key_press_trial_practice = [
        {
            question: "Same object?",
            picture: "images/1_50_different.jpg",
            number: 1,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/2_50_different.jpg",
            number: 2,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/3_50_different.jpg",
            number: 3,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/1_150_different.jpg",
            number: 1,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/2_150_different.jpg",
            number: 2,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/3_150_different.jpg",
            number: 3,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/1_50_same.jpg",
            number: 1,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/2_50_same.jpg",
            number: 2,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/3_50_same.jpg",
            number: 3,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/1_150_same.jpg",
            number: 1,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/2_150_same.jpg",
            number: 2,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/3_150_same.jpg",
            number: 3,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        }
    ];


const key_press_trial_main = [       
        {
            question: "Same object?",
            picture: "images/4_50_different.jpg",
            number: 4,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/5_50_different.jpg",
            number: 5,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/6_50_different.jpg",
            number: 6,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/7_50_different.jpg",
            number: 7,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/8_50_different.jpg",
            number: 8,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/9_50_different.jpg",
            number: 9,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/10_50_different.jpg",
            number: 10,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/11_50_different.jpg",
            number: 11,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/12_50_different.jpg",
            number: 12,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/13_50_different.jpg",
            number: 13,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/14_50_different.jpg",
            number: 14,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/15_50_different.jpg",
            number: 15,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/4_150_different.jpg",
            number: 4,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/5_150_different.jpg",
            number: 5,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/6_150_different.jpg",
            number: 6,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/7_150_different.jpg",
            number: 7,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/8_150_different.jpg",
            number: 8,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/9_150_different.jpg",
            number: 9,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/10_150_different.jpg",
            number: 10,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/11_150_different.jpg",
            number: 11,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/12_150_different.jpg",
            number: 12,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/13_150_different.jpg",
            number: 13,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/14_150_different.jpg",
            number: 14,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/15_150_different.jpg",
            number: 15,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'different'
        },
        {
            question: "Same object?",
            picture: "images/4_50_same.jpg",
            number: 4,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/5_50_same.jpg",
            number: 5,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/6_50_same.jpg",
            number: 6,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/7_50_same.jpg",
            number: 7,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/8_50_same.jpg",
            number: 8,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/9_50_same.jpg",
            number: 9,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/10_50_same.jpg",
            number: 10,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/11_50_same.jpg",
            number: 11,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/12_50_same.jpg",
            number: 12,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/13_50_same.jpg",
            number: 13,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/14_50_same.jpg",
            number: 14,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/15_50_same.jpg",
            number: 15,
            degree_of_rotation: 50,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/4_150_same.jpg",
            number: 4,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/5_150_same.jpg",
            number: 5,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/6_150_same.jpg",
            number: 6,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/7_150_same.jpg",
            number: 7,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/8_150_same.jpg",
            number: 8,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/9_150_same.jpg",
            number: 9,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/10_150_same.jpg",
            number: 10,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/11_150_same.jpg",
            number: 11,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/12_150_same.jpg",
            number: 12,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/13_150_same.jpg",
            number: 13,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/14_150_same.jpg",
            number: 14,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        },
        {
            question: "Same object?",
            picture: "images/15_150_same.jpg",
            number: 15,
            degree_of_rotation: 150,
            key1: 'y',
            key2: 'n',
            y: 'same',
            n: 'different',
            expected: 'same'
        }       
    ];
